# Generated by Django 5.1.15 on 2026-03-27 17:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField(help_text='What the AI will read out loud')),
                ('scheduled_at', models.DateTimeField(help_text='Exact UTC time to place the call')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('triggered', 'Triggered'), ('answered', 'Answered'), ('missed', 'Missed')], default='pending', max_length=20)),
                ('retell_call_id', models.CharField(blank=True, default='', max_length=255)),
                ('is_recurring', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'reminders_reminder',
                'ordering': ['scheduled_at'],
            },
        ),
    ]
