# Generated by Django 5.1.15 on 2026-03-29 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='scheduled_at',
            field=models.DateTimeField(),
        ),
    ]
